/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/element.dart';

/// The first lines of every API dump.
const apiDumpHeader =
    '// Public API of this package, generated by Inspectra. Do not edit by hand.\n'
    '// Regenerate it with "dart run build_runner build" or "dart run inspectra api dump".\n';

/// Renders the public API of [libraries] as a stable, reviewable text.
///
/// The API of a Dart library is its export namespace: everything it declares
/// or re-exports whose name does not start with an underscore. Each library
/// is rendered with all of those declarations, sorted by name, and each
/// declaration with its public members, sorted by kind and name - so the
/// dump changes exactly when the API does, and not when a declaration moves
/// between files below `lib/src`.
///
/// Declarations and members annotated with one of [nonPublicAnnotations] are
/// left out, which is how an API that must be public for technical reasons
/// is kept out of the contract.
String renderApi(
  Iterable<LibraryElement> libraries, {
  Iterable<String> nonPublicAnnotations = const [],
}) {
  final renderer = ApiRenderer(nonPublicAnnotations.toSet());
  final List<LibraryElement> sorted = libraries.toList()
    ..sort((a, b) => '${a.uri}'.compareTo('${b.uri}'));
  final buffer = StringBuffer(apiDumpHeader);
  for (final library in sorted) {
    buffer
      ..writeln()
      ..write(renderer.library(library));
  }
  return buffer.toString();
}

/// Renders libraries, types and members into the lines of an API dump.
///
/// One renderer is created per dump, so that the set of annotations that
/// hide a declaration is resolved once and shared by every library.
class ApiRenderer {
  /// Creates a renderer that leaves out every declaration annotated with one
  /// of the [_nonPublicAnnotations].
  ApiRenderer(this._nonPublicAnnotations);

  /// The indentation of a member below its type.
  static const _indent = '  ';

  /// The names of the annotations that keep a declaration out of the dump,
  /// such as `internal` or `visibleForTesting`.
  final Set<String> _nonPublicAnnotations;

  /// Renders the export namespace of [library]: a `library` line followed by
  /// every public declaration, sorted by name and separated by blank lines.
  String library(LibraryElement library) {
    final buffer = StringBuffer()..writeln('library ${library.uri}');
    final Map<String, Element> namespace =
        library.exportNamespace.definedNames2;
    final List<String> names = namespace.keys.toList()..sort();
    for (final name in names) {
      final Element element = namespace[name]!;
      if (!_isPublic(element)) {
        continue;
      }
      final String? rendered = _topLevel(element);
      if (rendered == null) {
        continue;
      }
      buffer
        ..writeln()
        ..writeln(rendered);
    }
    return buffer.toString();
  }

  /// Whether [element] belongs to the API: its name is public and none of its
  /// annotations is one of the [_nonPublicAnnotations].
  bool _isPublic(Element element) {
    if (element.isPrivate) {
      return false;
    }
    for (final ElementAnnotation annotation in element.metadata.annotations) {
      final Element? annotationElement = annotation.element;
      final String? name = annotationElement is ConstructorElement
          ? annotationElement.enclosingElement.name
          : annotationElement?.name;
      if (name != null && _nonPublicAnnotations.contains(name)) {
        return false;
      }
    }
    return true;
  }

  /// Renders the top-level [element], or returns `null` when it is rendered
  /// as part of another declaration, as the setter of a top-level variable is.
  String? _topLevel(Element element) => switch (element) {
    InterfaceElement() => _type(element),
    ExtensionElement() => _type(element),
    GetterElement(isOriginVariable: true) =>
      '${_deprecated(element)}${_variable(element.variable)};',
    SetterElement(isOriginVariable: true) => null,
    Element() => '${_deprecated(element)}${_executable(element)};',
  };

  /// Renders the type or extension [element] with its public members, one
  /// member per line and indented by [_indent].
  String _type(InstanceElement element) {
    final List<String> members = _members(element);
    final header = '${_deprecated(element)}${element.displayString()}';
    if (members.isEmpty) {
      return '$header {}';
    }
    final buffer = StringBuffer('$header {\n');
    for (final member in members) {
      buffer
        ..write(_indent)
        ..writeln(member);
    }
    buffer.write('}');
    return buffer.toString();
  }

  /// The rendered public members of [element], grouped and sorted so that
  /// the order is stable: enum constants, fields, constructors, accessors and
  /// methods.
  List<String> _members(InstanceElement element) {
    final constants = <String>[];
    final fields = <String>[];
    final constructors = <String>[];
    final accessors = <String>[];
    final methods = <String>[];

    for (final FieldElement field in element.fields) {
      if (!_isPublic(field)) {
        continue;
      }
      if (field.isEnumConstant) {
        constants.add('${_deprecated(field)}${field.name}');
        continue;
      }
      if (field.isOriginDeclaration && !_isRepresentation(element, field)) {
        fields.add('${_deprecated(field)}${_variable(field)};');
      }
    }
    if (element is InterfaceElement && element is! EnumElement) {
      for (final ConstructorElement constructor in element.constructors) {
        if (constructor.isOriginDeclaration && _isPublic(constructor)) {
          constructors.add(
            '${_deprecated(constructor)}${_constructor(constructor)};',
          );
        }
      }
    }
    for (final PropertyAccessorElement accessor in [
      ...element.getters,
      ...element.setters,
    ]) {
      if (accessor.isOriginDeclaration && _isPublic(accessor)) {
        accessors.add('${_deprecated(accessor)}${_executable(accessor)};');
      }
    }
    for (final MethodElement method in element.methods) {
      if (method.isOriginDeclaration && _isPublic(method)) {
        methods.add('${_deprecated(method)}${_executable(method)};');
      }
    }

    return [
      if (constants.isNotEmpty) '${constants.join(', ')};',
      ...fields..sort(_byName),
      ...constructors..sort(),
      ...accessors..sort(_byName),
      ...methods..sort(_byName),
    ];
  }

  /// Whether [field] is the representation field of the extension type
  /// [element], which is already part of its rendered header.
  bool _isRepresentation(InstanceElement element, FieldElement field) =>
      element is ExtensionTypeElement && element.representation == field;

  /// Renders [constructor] with its `external`, `const` and `factory`
  /// modifiers.
  String _constructor(ConstructorElement constructor) {
    final modifiers = [
      if (constructor.isExternal) 'external',
      if (constructor.isConst) 'const',
      if (constructor.isFactory) 'factory',
    ];
    return [...modifiers, constructor.displayString()].join(' ');
  }

  /// Renders [variable] with its modifiers and, for a constant, its value,
  /// since changing a constant value changes the API.
  String _variable(PropertyInducingElement variable) {
    final modifiers = [
      if (variable is FieldElement && variable.isExternal) 'external',
      if (variable is TopLevelVariableElement && variable.isExternal)
        'external',
      if (variable is FieldElement && variable.isAbstract) 'abstract',
      if (variable.isStatic && variable is FieldElement) 'static',
      if (variable is FieldElement && variable.isCovariant) 'covariant',
      if (variable.isLate) 'late',
      if (variable.isConst) 'const',
      if (!variable.isConst && variable.isFinal) 'final',
    ];
    final String declaration = [
      ...modifiers,
      variable.displayString(),
    ].join(' ');
    final Expression? value = variable.isConst
        ? variable.constantInitializer
        : null;
    return value == null ? declaration : '$declaration = ${value.toSource()}';
  }

  /// Renders the function, method or accessor [element] with its `external`,
  /// `static` and `abstract` modifiers; an operator gets its `operator`
  /// keyword back, which the analyzer leaves out of the display string.
  String _executable(Element element) {
    if (element is! ExecutableElement) {
      return element.displayString();
    }
    final modifiers = [
      if (element.isExternal) 'external',
      if (element.isStatic && element.enclosingElement is InstanceElement)
        'static',
      if (element.isAbstract) 'abstract',
    ];
    String signature = element.displayString();
    if (element is MethodElement && element.isOperator) {
      signature = signature.replaceFirst(
        '${element.name}(',
        'operator ${element.name}(',
      );
    }
    return [...modifiers, signature].join(' ');
  }

  /// The `@Deprecated` prefix when [element] is deprecated, otherwise an
  /// empty string.
  String _deprecated(Element element) =>
      element.metadata.hasDeprecated ? '@Deprecated ' : '';

  /// Compares the rendered members [a] and [b] by their name, see
  /// [_sortKey].
  static int _byName(String a, String b) => _sortKey(a).compareTo(_sortKey(b));

  /// Sorts members by name rather than by their leading modifiers or type,
  /// so that changing a return type changes a line but never its position.
  static String _sortKey(String signature) {
    final String beforeParameters = signature
        .split('(')
        .first
        .replaceAll(RegExp('<[^<>]*>'), '');
    final List<String> words = beforeParameters
        .replaceAll(';', '')
        .trim()
        .split(' ');
    return '${words.last} $signature';
  }
}
