import 'package:analyzer/dart/element/element.dart';

/// The first lines of every API dump.
const apiDumpHeader =
    '// Public API of this package, generated by Inspectra. Do not edit by hand.\n'
    '// Regenerate it with "dart run build_runner build" or "dart run inspectra api dump".\n';

/// Renders the public API of [libraries] as a stable, reviewable text.
///
/// The API of a Dart library is its export namespace: everything it declares
/// or re-exports whose name does not start with an underscore. Each library
/// is rendered with all of those declarations, sorted by name, and each
/// declaration with its public members, sorted by kind and name - so the
/// dump changes exactly when the API does, and not when a declaration moves
/// between files below `lib/src`.
///
/// Declarations and members annotated with one of [nonPublicAnnotations] are
/// left out, which is how an API that must be public for technical reasons
/// is kept out of the contract.
String renderApi(
  Iterable<LibraryElement> libraries, {
  Iterable<String> nonPublicAnnotations = const [],
}) {
  final renderer = _ApiRenderer(nonPublicAnnotations.toSet());
  final List<LibraryElement> sorted = libraries.toList()
    ..sort((a, b) => '${a.uri}'.compareTo('${b.uri}'));
  final buffer = StringBuffer(apiDumpHeader);
  for (final library in sorted) {
    buffer
      ..writeln()
      ..write(renderer.library(library));
  }
  return buffer.toString();
}

class _ApiRenderer {
  _ApiRenderer(this._nonPublicAnnotations);

  static const _indent = '  ';

  final Set<String> _nonPublicAnnotations;

  String library(LibraryElement library) {
    final buffer = StringBuffer()..writeln('library ${library.uri}');
    final Map<String, Element> namespace =
        library.exportNamespace.definedNames2;
    final List<String> names = namespace.keys.toList()..sort();
    for (final name in names) {
      final Element element = namespace[name]!;
      if (!_isPublic(element)) {
        continue;
      }
      final String? rendered = _topLevel(element);
      if (rendered == null) {
        continue;
      }
      buffer
        ..writeln()
        ..writeln(rendered);
    }
    return buffer.toString();
  }

  bool _isPublic(Element element) {
    if (element.isPrivate) {
      return false;
    }
    for (final ElementAnnotation annotation in element.metadata.annotations) {
      final Element? annotationElement = annotation.element;
      final String? name = switch (annotationElement) {
        ConstructorElement(:final enclosingElement) => enclosingElement.name,
        _ => annotationElement?.name,
      };
      if (name != null && _nonPublicAnnotations.contains(name)) {
        return false;
      }
    }
    return true;
  }

  String? _topLevel(Element element) => switch (element) {
    InterfaceElement() => _type(element),
    ExtensionElement() => _type(element),
    GetterElement(isOriginVariable: true) =>
      '${_deprecated(element)}${_variable(element.variable)};',
    SetterElement(isOriginVariable: true) => null,
    Element() => '${_deprecated(element)}${_executable(element)};',
  };

  String _type(InstanceElement element) {
    final List<String> members = _members(element);
    final header = '${_deprecated(element)}${element.displayString()}';
    if (members.isEmpty) {
      return '$header {}';
    }
    final buffer = StringBuffer('$header {\n');
    for (final member in members) {
      buffer
        ..write(_indent)
        ..writeln(member);
    }
    buffer.write('}');
    return buffer.toString();
  }

  List<String> _members(InstanceElement element) {
    final constants = <String>[];
    final fields = <String>[];
    final constructors = <String>[];
    final accessors = <String>[];
    final methods = <String>[];

    for (final FieldElement field in element.fields) {
      if (!_isPublic(field)) {
        continue;
      }
      if (field.isEnumConstant) {
        constants.add('${_deprecated(field)}${field.name}');
      } else if (field.isOriginDeclaration &&
          !_isRepresentation(element, field)) {
        fields.add('${_deprecated(field)}${_variable(field)};');
      }
    }
    if (element is InterfaceElement && element is! EnumElement) {
      for (final ConstructorElement constructor in element.constructors) {
        if (constructor.isOriginDeclaration &&
            _isPublic(constructor) &&
            !constructor.isPrimary) {
          constructors.add(
            '${_deprecated(constructor)}${_constructor(constructor)};',
          );
        }
      }
    }
    for (final PropertyAccessorElement accessor in [
      ...element.getters,
      ...element.setters,
    ]) {
      if (accessor.isOriginDeclaration && _isPublic(accessor)) {
        accessors.add('${_deprecated(accessor)}${_executable(accessor)};');
      }
    }
    for (final MethodElement method in element.methods) {
      if (method.isOriginDeclaration && _isPublic(method)) {
        methods.add('${_deprecated(method)}${_executable(method)};');
      }
    }

    return [
      if (constants.isNotEmpty) '${constants.join(', ')};',
      ...fields..sort(_byName),
      ...constructors..sort(),
      ...accessors..sort(_byName),
      ...methods..sort(_byName),
    ];
  }

  bool _isRepresentation(InstanceElement element, FieldElement field) =>
      element is ExtensionTypeElement && element.representation == field;

  String _constructor(ConstructorElement constructor) {
    final modifiers = [
      if (constructor.isExternal) 'external',
      if (constructor.isConst) 'const',
      if (constructor.isFactory) 'factory',
    ];
    return [...modifiers, constructor.displayString()].join(' ');
  }

  String _variable(PropertyInducingElement variable) {
    final modifiers = [
      if (variable is FieldElement && variable.isExternal) 'external',
      if (variable is TopLevelVariableElement && variable.isExternal)
        'external',
      if (variable is FieldElement && variable.isAbstract) 'abstract',
      if (variable.isStatic && variable is FieldElement) 'static',
      if (variable is FieldElement && variable.isCovariant) 'covariant',
      if (variable.isLate) 'late',
      if (variable.isConst) 'const' else if (variable.isFinal) 'final',
    ];
    return [...modifiers, variable.displayString()].join(' ');
  }

  String _executable(Element element) {
    if (element is! ExecutableElement) {
      return element.displayString();
    }
    final modifiers = [
      if (element.isExternal) 'external',
      if (element.isStatic && element.enclosingElement is InstanceElement)
        'static',
      if (element.isAbstract) 'abstract',
    ];
    String signature = element.displayString();
    if (element is MethodElement && element.isOperator) {
      signature = signature.replaceFirst(
        '${element.name}(',
        'operator ${element.name}(',
      );
    }
    return [...modifiers, signature].join(' ');
  }

  String _deprecated(Element element) =>
      element.metadata.hasDeprecated ? '@Deprecated ' : '';

  static int _byName(String a, String b) => _sortKey(a).compareTo(_sortKey(b));

  /// Sorts members by name rather than by their leading modifiers or type,
  /// so that changing a return type changes a line but never its position.
  static String _sortKey(String signature) {
    final String beforeParameters = signature
        .split('(')
        .first
        .replaceAll(RegExp('<[^<>]*>'), '');
    final List<String> words = beforeParameters
        .replaceAll(';', '')
        .trim()
        .split(' ');
    return '${words.last} $signature';
  }
}
