/*
 * Copyright 2026 Redtronics
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import 'dart:convert';
import 'dart:io';

import 'package:inspectra/src/model/inspectra_exception.dart';
import 'package:inspectra/src/style/style_host_answer.dart';
import 'package:inspectra/src/style/style_violation.dart';
import 'package:inspectra/src/util/dart_tool.dart';
import 'package:path/path.dart' as p;

/// Runs the custom style rules of a package in a program of their own.
///
/// Custom rules are Dart code of the package, which a running Inspectra -
/// possibly a compiled executable - cannot load. Like analyzer plugins,
/// Inspectra therefore generates a small program in
/// `.dart_tool/inspectra/style/` that imports the rule files and calls
/// `runStyleHost`, and runs it with `dart run` in the package, where
/// `package:inspectra` and the rules' own imports resolve.
final class StyleHost {
  /// Creates a host for the package in [packageRoot].
  const StyleHost(this.packageRoot);

  /// The package root.
  final String packageRoot;

  /// The directory of the generated program, relative to the package root.
  static const directory = '.dart_tool/inspectra/style';

  /// Runs the rules declared in [ruleFiles] on [files], except the rules
  /// whose ids are in [disabled]. All paths are relative to the package
  /// root.
  ///
  /// Returns the rules and their violations.
  ///
  /// Throws an [InvalidInputException] when a rule file is missing or the
  /// rules cannot be compiled or run, and an [UnavailableException] when
  /// `dart` cannot be started.
  Future<StyleHostAnswer> run({
    required List<String> ruleFiles,
    required List<String> files,
    required Set<String> disabled,
  }) async {
    for (final file in ruleFiles) {
      if (!File(p.join(packageRoot, file)).existsSync()) {
        throw InvalidInputException(
          'The custom style rules $file (style.custom_rules) do not exist.',
        );
      }
    }
    final hostDirectory = Directory(p.join(packageRoot, directory));
    await hostDirectory.create(recursive: true);
    final program = File(p.join(hostDirectory.path, 'host.dart'));
    final request = File(p.join(hostDirectory.path, 'request.json'));
    final answer = File(p.join(hostDirectory.path, 'answer.json'));
    await program.writeAsString(hostProgram(ruleFiles));
    await request.writeAsString(
      jsonEncode(<String, Object?>{
        'root': p.absolute(packageRoot),
        'files': files,
        'disabled': disabled.toList()..sort(),
        'output': answer.absolute.path,
      }),
    );
    if (answer.existsSync()) {
      await answer.delete();
    }
    final ProcessResult result = await _runDart(<String>[
      'run',
      p.posix.join(directory, 'host.dart'),
      p.posix.join(directory, 'request.json'),
    ]);
    if (result.exitCode != 0 || !answer.existsSync()) {
      throw InvalidInputException(
        'The custom style rules of style.custom_rules could not be run '
        '(dart run exited with ${result.exitCode}). Each file must declare '
        'a top level "styleRules" of type List<StyleRule>, and the package '
        'must depend on inspectra and be resolved with "dart pub get".\n'
        '${_tail('${result.stderr}${result.stdout}')}',
      );
    }
    return _read(await answer.readAsString());
  }

  /// Generates the program that imports [ruleFiles] and runs their rules.
  ///
  /// Returns the Dart source.
  static String hostProgram(List<String> ruleFiles) {
    final out = StringBuffer()
      ..writeln('// Generated by Inspectra to run the custom style rules.')
      ..writeln('// Regenerated on every run; do not edit.')
      ..writeln()
      ..writeln("import 'package:inspectra/style.dart';");
    for (var index = 0; index < ruleFiles.length; index++) {
      final String relative = p.posix.relative(
        ruleFiles[index].replaceAll(r'\', '/'),
        from: directory,
      );
      out.writeln("import '$relative' as rules$index;");
    }
    out
      ..writeln()
      ..writeln('Future<void> main(List<String> arguments) =>')
      ..writeln('    runStyleHost(arguments, <StyleRule>[');
    for (var index = 0; index < ruleFiles.length; index++) {
      out.writeln('      ...rules$index.styleRules,');
    }
    out.writeln('    ]);');
    return out.toString();
  }

  /// Runs `dart` with [arguments] in the package root.
  ///
  /// Returns the outcome.
  ///
  /// Throws an [UnavailableException] when `dart` cannot be started.
  Future<ProcessResult> _runDart(List<String> arguments) async {
    try {
      return await runDart(arguments, workingDirectory: packageRoot);
    } on DartToolException catch (error) {
      throw UnavailableException(error.message);
    }
  }

  /// Parses the [json] answer of the program.
  ///
  /// Returns the answer.
  ///
  /// Throws an [InvalidInputException] when the rules reported a problem
  /// or the answer is malformed.
  StyleHostAnswer _read(String json) {
    final Object? decoded = jsonDecode(json);
    if (decoded is! Map<String, Object?>) {
      throw const InvalidInputException(
        'The custom style rules returned a malformed answer.',
      );
    }
    final Object? error = decoded['error'];
    if (error is String) {
      throw InvalidInputException(error);
    }
    final Object? rules = decoded['rules'];
    final Object? violations = decoded['violations'];
    if (rules is! List<Object?> || violations is! List<Object?>) {
      throw const InvalidInputException(
        'The custom style rules returned a malformed answer.',
      );
    }
    return StyleHostAnswer(
      rules: <String, String>{
        for (final Object? rule in rules)
          if (rule is Map<String, Object?>)
            '${rule['id']}': '${rule['description']}',
      },
      violations: <StyleViolation>[
        for (final Object? violation in violations)
          StyleViolation.fromJson(violation),
      ],
    );
  }

  /// Returns the last lines of [output], enough to show a compile error.
  static String _tail(String output) {
    final List<String> lines = output.trim().split('\n');
    return lines.skip(lines.length > 20 ? lines.length - 20 : 0).join('\n');
  }
}
