/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import 'dart:io';

import 'package:inspectra/inspectra.dart';
import 'package:test/test.dart';

/// Tests reading an API dump back into its declarations.
void main() {
  const dump = '''
// Public API of this package, generated by Inspectra. Do not edit by hand.

library package:shapes/shapes.dart

const int sides = 4;

double area(Shape shape, [int precision = 2]);

typedef Measure = double Function(Shape shape);

abstract base class Shape<T extends Object> implements Comparable<Shape> {
  abstract double get area;
  const Shape();
  const Shape.unit({int size = 1});
  static Shape? parse(String text);
  bool operator ==(Object other);
  set label(String value);
  @Deprecated String get name;
}

enum Color {
  red, green;
  final int code;
  String get label;
}

final class Empty {}

extension ShapeList on List<Shape> {
  double get total;
}

extension on String {
  int get twice;
}

extension type Id(int value) {}

library package:shapes/extra.dart

@Deprecated mixin class Painter {}
''';

  late ApiSurface surface;

  setUp(() => surface = ApiSurface.parse(dump));

  test('reads the libraries and their declarations', () {
    expect(surface.libraries.keys, <String>[
      'package:shapes/shapes.dart',
      'package:shapes/extra.dart',
    ]);
    expect(surface.libraries['package:shapes/shapes.dart']!.keys, <String>[
      'sides',
      'area',
      'Measure',
      'Shape',
      'Color',
      'Empty',
      'ShapeList',
      'extension on String',
      'Id',
    ]);
    expect(surface.libraries['package:shapes/extra.dart']!.keys, <String>[
      'Painter',
    ]);
  });

  test('keys the members by name, accessor and operator', () {
    final ApiDeclaration shape =
        surface.libraries['package:shapes/shapes.dart']!['Shape']!;
    expect(shape.isType, isTrue);
    expect(
      shape.line,
      'abstract base class Shape<T extends Object> implements '
      'Comparable<Shape>',
    );
    expect(shape.members.keys, <String>[
      'get area',
      'Shape',
      'Shape.unit',
      'parse',
      'operator ==',
      'set label',
      'get name',
    ]);
    expect(shape.members['get name'], '@Deprecated String get name;');
  });

  test('reads enum values apart from the members', () {
    final ApiDeclaration color =
        surface.libraries['package:shapes/shapes.dart']!['Color']!;
    expect(color.values, <String>['red', 'green']);
    expect(color.members.keys, <String>['code', 'get label']);
  });

  test('reads empty types and top-level lines', () {
    final Map<String, ApiDeclaration> shapes =
        surface.libraries['package:shapes/shapes.dart']!;
    expect(shapes['Empty']!.isType, isTrue);
    expect(shapes['Empty']!.members, isEmpty);
    expect(shapes['Id']!.line, 'extension type Id(int value)');
    expect(shapes['sides']!.isType, isFalse);
    expect(shapes['sides']!.line, 'const int sides = 4;');
    expect(
      surface.libraries['package:shapes/extra.dart']!['Painter']!.line,
      '@Deprecated mixin class Painter',
    );
  });

  test('keeps declarations before any library line', () {
    expect(
      ApiSurface.parse('int answer();\n').libraries[''],
      contains('answer'),
    );
  });

  test('names declarations and members', () {
    expect(ApiSurface.typeName('sealed class Result<T>'), 'Result');
    expect(ApiSurface.typeName('mixin class Painter'), 'Painter');
    expect(ApiSurface.typeName('extension type Id(int value)'), 'Id');
    expect(ApiSurface.typeName('extension on int'), 'extension on int');
    expect(ApiSurface.typeName('something else'), 'something else');
    expect(ApiSurface.keyOf('final Map<String, int> counts;'), 'counts');
    expect(ApiSurface.keyOf('void run(void Function(int) callback);'), 'run');
    expect(ApiSurface.keyOf("const String id = 'a = b';"), 'id');
    expect(ApiSurface.keyOf('typedef Json = Map<String, Object?>;'), 'Json');
    expect(
      ApiSurface.keyOf('List<int> operator [](int index);'),
      'operator []',
    );
  });

  test('finds text outside of brackets and quotes', () {
    expect(ApiSurface.topLevelIndexOf('f(a = 1) = 2', ' = '), 8);
    expect(ApiSurface.topLevelIndexOf("'a, b', c", ','), 6);
    expect(ApiSurface.topLevelIndexOf('<a, b>', ','), -1);
    expect(ApiSurface.openingOf('f(g(x))', 6), 1);
    expect(ApiSurface.openingOf('x)', 1), 0);
  });

  test('reads the committed dump of Inspectra itself', () {
    final surface = ApiSurface.parse(
      File('api/inspectra.api').readAsStringSync(),
    );
    final Map<String, ApiDeclaration> library =
        surface.libraries['package:inspectra/inspectra.dart']!;
    expect(library['Severity']!.values, contains('critical'));
    expect(library['ApiConfig']!.members, contains('ApiConfig.fromYaml'));
  });
}
