/*
 * Copyright 2026 Redtronics
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/// Widely used pub.dev packages that typosquatting attacks imitate.
///
/// A dependency whose name is itself on this list is never reported, which
/// is why popular packages that happen to be close to each other, such as
/// `lints` and `intl` or `http` and `http2`, are both listed. Organisations
/// can extend the list with `typosquat.popular` and silence false positives
/// with `typosquat.allow`.
final class PopularPackages {
  /// Prevents instantiation; this type only offers the name list.
  const PopularPackages._();

  /// The built-in list of popular package names.
  static const Set<String> names = <String>{
    'analyzer',
    'animations',
    'archive',
    'args',
    'async',
    'audioplayers',
    'auto_route',
    'auto_route_generator',
    'badges',
    'battery_plus',
    'beamer',
    'bloc',
    'bloc_test',
    'build',
    'build_runner',
    'cached_network_image',
    'camera',
    'carousel_slider',
    'characters',
    'chopper',
    'clock',
    'cloud_firestore',
    'collection',
    'connectivity_plus',
    'convert',
    'cookie_jar',
    'crypto',
    'csv',
    'cupertino_icons',
    'dartz',
    'device_info_plus',
    'dio',
    'dio_cookie_manager',
    'drift',
    'drift_dev',
    'easy_localization',
    'encrypt',
    'envied',
    'equatable',
    'fake_async',
    'ffi',
    'file',
    'file_picker',
    'firebase_analytics',
    'firebase_auth',
    'firebase_core',
    'firebase_crashlytics',
    'firebase_messaging',
    'firebase_storage',
    'fl_chart',
    'flutter',
    'flutter_animate',
    'flutter_bloc',
    'flutter_cache_manager',
    'flutter_dotenv',
    'flutter_driver',
    'flutter_form_builder',
    'flutter_hooks',
    'flutter_inappwebview',
    'flutter_launcher_icons',
    'flutter_lints',
    'flutter_local_notifications',
    'flutter_localizations',
    'flutter_map',
    'flutter_mobx',
    'flutter_native_splash',
    'flutter_riverpod',
    'flutter_screenutil',
    'flutter_secure_storage',
    'flutter_slidable',
    'flutter_staggered_grid_view',
    'flutter_svg',
    'flutter_test',
    'flutter_typeahead',
    'flutter_web_plugins',
    'font_awesome_flutter',
    'form_builder_validators',
    'fpdart',
    'freezed',
    'freezed_annotation',
    'gallery_saver',
    'gap',
    'geocoding',
    'geolocator',
    'get',
    'get_it',
    'get_storage',
    'glob',
    'go_router',
    'google_fonts',
    'google_maps',
    'google_maps_flutter',
    'google_mobile_ads',
    'google_sign_in',
    'graphql',
    'graphql_flutter',
    'grpc',
    'hive',
    'hive_flutter',
    'hive_generator',
    'hooks_riverpod',
    'html',
    'http',
    'http2',
    'http_mock_adapter',
    'http_parser',
    'hydrated_bloc',
    'image',
    'image_picker',
    'in_app_purchase',
    'injectable',
    'injectable_generator',
    'intl',
    'intl_utils',
    'io',
    'isar',
    'jiffy',
    'js',
    'json_annotation',
    'json_serializable',
    'just_audio',
    'latlong2',
    'lints',
    'local_auth',
    'location',
    'logger',
    'logging',
    'lottie',
    'mapbox_gl',
    'meta',
    'mobx',
    'mobile_scanner',
    'mockito',
    'mocktail',
    'moor',
    'objectbox',
    'open_filex',
    'package_info_plus',
    'path',
    'path_provider',
    'pdf',
    'permission_handler',
    'platform',
    'plugin_platform_interface',
    'pointycastle',
    'printing',
    'process',
    'protobuf',
    'provider',
    'pub_semver',
    'pubspec_parse',
    'pull_to_refresh',
    'qr_flutter',
    'reactive_forms',
    'responsive_builder',
    'retrofit',
    'rive',
    'riverpod',
    'riverpod_annotation',
    'riverpod_generator',
    'riverpod_lint',
    'rxdart',
    'sensors_plus',
    'sentry',
    'sentry_flutter',
    'share_plus',
    'shared_preferences',
    'shelf',
    'shelf_router',
    'shimmer',
    'sliver_tools',
    'slang',
    'source_gen',
    'source_span',
    'sqflite',
    'sqlite3',
    'sqlite3_flutter_libs',
    'stack_trace',
    'stream_transform',
    'string_scanner',
    'styled_widget',
    'supabase',
    'supabase_flutter',
    'test',
    'timeago',
    'url_launcher',
    'uuid',
    'vector_math',
    'very_good_analysis',
    'vibration',
    'video_player',
    'wakelock_plus',
    'watcher',
    'web',
    'web_socket_channel',
    'webview_flutter',
    'xml',
    'yaml',
    'yaml_edit',
  };
}
